Agregar cambios esterilización tramites y servicios
Ekisa-Team/esterilizacion pull request #19
Opened 2020-12-03 16:10 UTC by Alexisqu20

## Descripción

Agregara cambios a los módulos de eterización administración, tramites y servicios

## Tipo de cambio

Elimine las opciones que no sean relevantes.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## ¿Cómo se ha probado esto?

se probo de manera visual 

## Checklist:

- [x] Mi código sigue las pautas y estándares de este proyecto
- [x] He realizado una revisión y autoevaluación de mi propio código antes de subirlo
- [x] He documentado mi código, especialmente en áreas difíciles de entender
- [x] He realizado los cambios correspondientes a la documentación
- [ ] Mis cambios no generan nuevas advertencias ni errores
- [ ] He agregado pruebas que prueban que mi corrección es efectiva o que mi característica funciona
- [ ] Los cambios dependientes se han fusionado y publicado en módulos posteriores

2020-12-03 16:33 UTC, juanmesa2097 requested changes

2020-12-03 16:33 UTC, juanmesa2097 commented on client/src/app/admin/containers/instrumentos-inventario/instrumentos-inventario.page.ts
> +  bucarPersona(): void {
Acá debería ser "onClickBuscarPersona"

2020-12-04 22:40 UTC, juanmesa2097 requested changes

2020-12-04 22:40 UTC, juanmesa2097 commented on client/src/app/admin/containers/instrumentos-devolucion/instrumentos-devolucion.page.ts
> +  onClickBucarPerona(): void {
Hay un typo "Bucar"

2020-12-09 14:41 UTC, juanmesa2097 requested changes

2020-12-09 14:41 UTC, juanmesa2097 commented on client/src/app/tramites/containers/instrumentos-pedidos/instrumentos-pedidos.page.ts
>    OnClickDetalleSolicitud() {
El On está en mayúscula

2020-12-09 14:41 UTC, juanmesa2097 commented on client/src/app/admin/containers/instrumentos-devolucion/instrumentos-devolucion.page.html
> +                onClick: onClickBuscarPerona
"Perona"

2020-12-09 14:41 UTC, juanmesa2097 commented on client/src/app/admin/containers/instrumentos-inventario/instrumentos-inventario.page.html
> +                onClick: bucarPersona
"bucar"

2020-12-09 15:15 UTC, juanmesa2097 approved these changes

2020-12-09 15:59 UTC, checho4540 submitted a review, later dismissed

2020-12-09 19:05 UTC, juansechalarca submitted a review, later dismissed

2020-12-09 20:08 UTC, checho4540 approved these changes

2020-12-09 20:53 UTC, juansechalarca approved these changes

2020-12-09 21:00 UTC, juanmesa2097 approved these changes

2020-12-09 21:12 UTC, merged