Se crea modelo ProgramacionClinica
Ekisa-Team/esterilizacion pull request #25
Opened 2020-12-10 16:05 UTC by jonathan07-1991

Se crea nuevas clases y se agregan los servicios

2020-12-10 16:27 UTC, Alexisqu20 approved these changes

2020-12-10 16:33 UTC, Alexisqu20 approved these changes

2020-12-10 22:12 UTC, Alexisqu20 approved these changes

2020-12-10 22:18 UTC, napster1582 requested changes

2020-12-10 22:18 UTC, napster1582 commented on server/Interfaces/Services/ProgramacionClinica/IDiasSemanaService.cs
> +	    Response GetDiasSemana();
Identar linea

2020-12-10 22:18 UTC, napster1582 commented on server/Interfaces/Services/ProgramacionClinica/IDiasSemanaService.cs
> +
Quitar espacios

2020-12-10 22:18 UTC, napster1582 commented on server/Interfaces/Services/ProgramacionClinica/IProgramacionClinicasService.cs
> +	    Response GetProgramacionClinicas();
Identar linea

2020-12-10 22:18 UTC, napster1582 commented on server/Interfaces/Services/ProgramacionClinica/IProgramacionClinicasService.cs
> +
Quitar espacios

2020-12-11 15:37 UTC, juansechalarca approved these changes

2020-12-14 15:00 UTC, napster1582 approved these changes

2020-12-14 15:01 UTC, merged