feat: crear componente instrumentos solicitudes
Ekisa-Team/esterilizacion pull request #5
Opened 2020-11-18 14:37 UTC by juansechalarca

##Descripción 
- Se creo el componente instrumentos solicitudes

- [ ]  juan

- [ ] sergio

- [ ] alexis

2020-11-18 14:40 UTC, juanmesa2097 requested changes

2020-11-18 14:40 UTC, juanmesa2097 commented on client/src/app/admin/containers/instrumentos-mis-solicitudes/instrumentos-mis-solicitudes.page.html
> +    </div>
Todo muy bn pero faltó documentar el html xD

2020-11-18 14:47 UTC, juansechalarca commented on client/src/app/admin/containers/instrumentos-mis-solicitudes/instrumentos-mis-solicitudes.page.html
> +    </div>
ya lo documente jajaj, la costumbre XD

2020-11-18 14:50 UTC, juanmesa2097 approved these changes

2020-11-18 17:14 UTC, checho4540 approved these changes

2020-11-18 20:50 UTC, juanmesa2097 approved these changes

2020-11-19 14:26 UTC, Alexisqu20 approved these changes

2020-11-19 14:33 UTC, merged