feat: crear componentes clinica
Ekisa-Team/esterilizacion pull request #8
Opened 2020-11-18 22:22 UTC by checho4540

#Descripcion 
Se creo el componente y su respectivo diseño html

2020-11-18 22:37 UTC, juanmesa2097 requested changes
Todo está bien pero el código no está bien formateado.

- Verificar que prettier sea el formateador por defecto.
  - Si al guardar no formatea el código, entonces seleccionar todo el texto y presionar `shift + alt + f` y cuando salte la alerta de que no hay un formateador configurado, seleccionar prettier como formateador for defecto.
- Verificar que en la configuración de vscode el page size sea 2 para tener la identación correcta

![image](https://user-images.githubusercontent.com/64181348/99596343-1a822e00-29c4-11eb-87b9-afa0b5484926.png)

2020-11-18 22:37 UTC, juanmesa2097 commented on client/src/app/admin/containers/clinicas-lista/clinicas-lista.page.html
> +    <dx-data-grid id="gridContainer" [dataSource]="instrumentos" [masterDetail]="{ enabled: false, template: 'detail' }" keyExpr="id" [showBorders]="true" [columnHidingEnabled]="true">
Recomiendo quitar el id ya que solo se usa cuando este va a ser target de otro componente

2020-11-18 22:41 UTC, checho4540 commented on client/src/app/admin/containers/clinicas-lista/clinicas-lista.page.html
> +    <dx-data-grid id="gridContainer" [dataSource]="instrumentos" [masterDetail]="{ enabled: false, template: 'detail' }" keyExpr="id" [showBorders]="true" [columnHidingEnabled]="true">
Listo, ya hare las correcciones

2020-11-18 23:29 UTC, juanmesa2097 submitted a review, later dismissed

2020-11-19 14:58 UTC, Alexisqu20 submitted a review, later dismissed

2020-11-19 15:36 UTC, juansechalarca submitted a review, later dismissed

2020-11-19 17:49 UTC, juanmesa2097 approved these changes

2020-11-19 18:54 UTC, Alexisqu20 approved these changes

2020-11-19 18:54 UTC, Alexisqu20 approved these changes

2020-11-20 15:35 UTC, juansechalarca approved these changes

2020-11-20 15:36 UTC, merged